# Generated by Django 4.1.7 on 2023-06-22 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appPaseador', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calificacion',
            name='duenio',
        ),
        migrations.RemoveField(
            model_name='calificacion',
            name='paseador',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='duenio',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='mascotaId',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='paseador',
        ),
        migrations.RemoveField(
            model_name='paseador',
            name='paseadorUser',
        ),
        migrations.DeleteModel(
            name='administrador',
        ),
        migrations.DeleteModel(
            name='calificacion',
        ),
        migrations.DeleteModel(
            name='cita',
        ),
        migrations.DeleteModel(
            name='paseador',
        ),
    ]
