# Generated by Django 4.1.7 on 2023-06-22 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appPaseador', '0003_admininsertpaseador_administrador_paseador_cita_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cita',
        ),
    ]
