# Generated by Django 4.1.7 on 2023-06-22 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appPaseador', '0005_cita'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cita',
        ),
    ]
