# Generated by Django 4.1.7 on 2023-06-22 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appPaseador', '0006_delete_cita'),
    ]

    operations = [
        migrations.CreateModel(
            name='cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('hora', models.TimeField(auto_now=True)),
                ('precio', models.PositiveBigIntegerField(verbose_name='precio')),
                ('lugar', models.CharField(max_length=30)),
                ('duenio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appPaseador.duenio')),
                ('mascotaId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appPaseador.mascota')),
                ('paseador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appPaseador.paseador')),
            ],
        ),
    ]
